server {
    listen 80;
    listen [::]:80;
    server_name audio.deline.top;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        try_files $uri =404;
    }

    location / {
        return 503;
    }
}
